"""SQLite-backed search logic for the Wu pronunciation site."""

from __future__ import annotations

import re
import sqlite3
from contextlib import closing
from pathlib import Path
from typing import Iterable


DIALECTS = {
    "suhu": {
        "file": "DB_suhu.sqlite3",
        "name": "蘇滬混合腔",
        "romanization": True,
    },
    "qingmo": {
        "file": "DB_qingmo.sqlite3",
        "name": "清末蘇州話",
        "romanization": False,
    },
    "shanghai": {
        "file": "DB_shanghai.sqlite3",
        "name": "上海話",
        "romanization": False,
    },
    "suzhou": {
        "file": "DB_suzhou.sqlite3",
        "name": "蘇州話",
        "romanization": False,
    },
    "pingtan": {
        "file": "DB_pingtan.sqlite3",
        "name": "蘇州評彈音",
        "romanization": False,
    },
}

OU_TO_U_MAP = {
    "pou": "pu",
    "phou": "phu",
    "mou": "mu",
    "fou": "fu",
    "vou": "vu",
    "tou": "tu",
    "thou": "thu",
    "nou": "nu",
    "lou": "lu",
    "kou": "ku",
    "khou": "khu",
    "hou": "hu",
    "ghou": "wu",
    "ngou": "ngu",
    "tsou": "tsu",
    "tshou": "tshu",
    "sou": "su",
    "zou": "zu",
}

_TONE_AT_END = re.compile(r"[1-9]$")


class SearchService:
    """Read-only search service over the databases generated by get_data.c."""

    def __init__(self, data_directory: str | Path) -> None:
        self.data_directory = Path(data_directory).resolve()
        self.variant_database = self.data_directory / "S2T.sqlite3"
        self.reading_databases = {
            code: self.data_directory / str(details["file"])
            for code, details in DIALECTS.items()
        }
        self._check_files()

    def _check_files(self) -> None:
        required = [self.variant_database, *self.reading_databases.values()]
        missing = [str(path) for path in required if not path.is_file()]
        if missing:
            raise FileNotFoundError(
                "Missing SQLite database file(s): " + ", ".join(missing)
            )

    @staticmethod
    def _connect(path: Path) -> sqlite3.Connection:
        connection = sqlite3.connect(path.as_uri() + "?mode=ro", uri=True)
        connection.row_factory = sqlite3.Row
        connection.execute("PRAGMA query_only = ON")
        return connection

    def _traditional_targets(self, source_character: str) -> list[str]:
        with closing(self._connect(self.variant_database)) as connection:
            rows = connection.execute(
                """
                SELECT target_character
                FROM character_variants
                WHERE source_character = ? AND variant_type = 's2t'
                """,
                (source_character,),
            ).fetchall()
        return [str(row["target_character"]) for row in rows]

    def _expand_characters(self, text: str) -> list[dict[str, str]]:
        results: list[dict[str, str]] = []
        seen: set[str] = set()
        emitted: set[str] = set()

        for source in text:
            if source in seen:
                continue
            seen.add(source)
            targets = self._traditional_targets(source)

            if not targets:
                if source not in emitted:
                    results.append({"character": source, "source": "direct"})
                    emitted.add(source)
                continue

            for target in targets:
                if target == source:
                    if target not in emitted:
                        results.append({"character": target, "source": "direct"})
                        emitted.add(target)
                    continue
                if target in seen or target in emitted:
                    continue
                seen.add(target)
                emitted.add(target)
                results.append(
                    {
                        "character": target,
                        "source": "converted",
                        "from": source,
                    }
                )

        return results

    @staticmethod
    def _merge_readings(
        rows: Iterable[sqlite3.Row], has_romanization: bool
    ) -> list[dict[str, object]]:
        """Deduplicate readings within one character and one dialect.

        Romanized data uses (romanization, IPA) as its reading key. IPA-only
        data uses IPA. Notes and future audio paths are collected per group;
        neither input order nor output order is part of the API contract.
        """

        groups: dict[tuple[str, ...], dict[str, object]] = {}
        for row in rows:
            romanization = row["romanization"]
            ipa = row["ipa"]
            key = (
                (str(romanization or ""), str(ipa or ""))
                if has_romanization
                else (str(ipa or ""),)
            )
            group = groups.get(key)
            if group is None:
                group = {
                    "romanization": romanization,
                    "ipa": ipa,
                    "notes": set(),
                    "audio": set(),
                }
                groups[key] = group

            note = row["note"]
            audio = row["audio"]
            if note:
                group["notes"].add(str(note))  # type: ignore[union-attr]
            if audio:
                group["audio"].add(str(audio))  # type: ignore[union-attr]

        merged: list[dict[str, object]] = []
        for group in groups.values():
            notes = list(group["notes"])
            audio = list(group["audio"])
            merged.append(
                {
                    "romanization": group["romanization"],
                    "ipa": group["ipa"],
                    "note": "；".join(notes),
                    "audio": audio,
                }
            )
        return merged

    def _readings_for_character(
        self, character: str, dialect_code: str
    ) -> list[dict[str, object]]:
        details = DIALECTS[dialect_code]
        with closing(self._connect(self.reading_databases[dialect_code])) as connection:
            rows = connection.execute(
                """
                SELECT romanization, ipa, audio, note
                FROM readings
                WHERE character = ?
                """,
                (character,),
            ).fetchall()
        return self._merge_readings(rows, bool(details["romanization"]))

    @staticmethod
    def _selected_dialects(requested: Iterable[str] | None) -> list[str]:
        if requested is None:
            return list(DIALECTS)
        requested_set = {str(code) for code in requested}
        return [code for code in DIALECTS if code in requested_set]

    def search_characters(
        self, raw_text: str, requested_dialects: Iterable[str] | None = None
    ) -> dict[str, object]:
        text = raw_text.strip()
        if not text:
            raise ValueError("Please enter at least one character.")
        if len(text) > 8:
            raise ValueError("Maximum 8 characters at a time.")

        selected = self._selected_dialects(requested_dialects)
        characters = self._expand_characters(text)
        for item in characters:
            character = item["character"]
            item["readings"] = {
                code: self._readings_for_character(character, code)
                for code in selected
            }

        return {"characters": characters, "dialects": selected}

    @staticmethod
    def normalize_pinyin(raw_pinyin: str) -> tuple[str, str, bool]:
        normalized = raw_pinyin.strip().lower()
        if not normalized:
            raise ValueError("Please enter a romanization.")

        has_tone = bool(_TONE_AT_END.search(normalized))
        tone = normalized[-1] if has_tone else ""
        base = normalized[:-1] if has_tone else normalized
        base = OU_TO_U_MAP.get(base, base)
        full = base + tone if has_tone else base
        return full, base, has_tone

    def reverse_lookup(self, raw_pinyin: str) -> dict[str, object]:
        normalized, base, has_tone = self.normalize_pinyin(raw_pinyin)
        database = self.reading_databases["suhu"]

        if has_tone:
            sql = """
                SELECT character, romanization, ipa
                FROM readings
                WHERE lower(romanization) = ?
                ORDER BY romanization COLLATE NOCASE
            """
            parameters = (normalized,)
        else:
            sql = """
                SELECT character, romanization, ipa
                FROM readings
                WHERE lower(
                    CASE
                        WHEN substr(romanization, -1, 1) GLOB '[1-9]'
                        THEN substr(romanization, 1, length(romanization) - 1)
                        ELSE romanization
                    END
                ) = ?
                ORDER BY romanization COLLATE NOCASE
            """
            parameters = (base,)

        with closing(self._connect(database)) as connection:
            rows = connection.execute(sql, parameters).fetchall()

        grouped: dict[str, dict[str, object]] = {}
        for row in rows:
            reading = str(row["romanization"])
            group = grouped.get(reading)
            if group is None:
                group = {
                    "reading": reading,
                    "ipa": row["ipa"],
                    "characters": [],
                }
                grouped[reading] = group
            character = str(row["character"])
            characters = group["characters"]
            if character not in characters:
                characters.append(character)

        return {"query": normalized, "groups": list(grouped.values())}